# Generated by Django 2.2 on 2019-12-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191204_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
