# Generated by Django 2.2 on 2019-12-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191205_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='recommend',
            field=models.ManyToManyField(related_name='rc', to='api.Course'),
        ),
    ]
