# Generated by Django 2.2 on 2019-11-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbactools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=64),
        ),
    ]
