# Generated by Django 2.2 on 2019-10-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_permission_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
