# Generated by Django 2.2 on 2019-09-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_tese'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tese',
            new_name='Test',
        ),
    ]
