# Generated by Django 2.2 on 2019-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='无敌东路', max_length=200),
            preserve_default=False,
        ),
    ]
