# Generated by Django 2.2 on 2019-11-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_futhurdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futhurdetail',
            old_name='market',
            new_name='consultant',
        ),
    ]
