# Generated by Django 2.2 on 2019-11-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=64, unique=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
    ]
